//! Validation of JSON values against the JSON Schemas advertised by the
//! TypeScript server, using Zod parsing semantics.
//!
//! The advertised schemas were generated by Zod, so interpreting them with the
//! same rules reproduces the original runtime behavior:
//! - objects strip unknown keys unless `additionalProperties` is `{}` (passthrough)
//! - output key order follows the schema shape, then passthrough keys
//! - issue messages match Zod 4's English locale

use crate::js;
use serde_json::{Map, Value};

const MAX_SAFE_INTEGER: f64 = 9_007_199_254_740_991.0;

const ID_PATTERN: &str = "^[a-zA-Z0-9_-]+$";
const OFFSET_PATTERN: &str = r"^[+-](?:0\d|1[0-4]):[0-5]\d$";
const ISO_PATTERN: &str =
    r"^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d{1,3})?(Z|[+-]\d{2}:\d{2})?)?$";
const DATETIME_PATTERN: &str = r"^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z|([+-](?:[01]\d|2[0-3]):[0-5]\d)))$";

/// One segment of an issue path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PathSeg {
    Key(String),
    Index(usize),
}

/// A validation issue in Zod's shape.
#[derive(Debug, Clone, PartialEq)]
pub struct Issue {
    /// Zod issue fields preceding `path` (e.g. `expected`, `code`).
    pub fields: Vec<(&'static str, Value)>,
    pub path: Vec<PathSeg>,
    pub message: String,
}

impl Issue {
    fn new(fields: Vec<(&'static str, Value)>, path: &[PathSeg], message: String) -> Self {
        Self {
            fields,
            path: path.to_vec(),
            message,
        }
    }

    /// Serialize like a Zod issue object.
    pub fn to_json(&self) -> Value {
        let mut map = Map::new();
        for (key, value) in &self.fields {
            map.insert((*key).to_string(), value.clone());
        }
        let path = self
            .path
            .iter()
            .map(|seg| match seg {
                PathSeg::Key(k) => Value::from(k.clone()),
                PathSeg::Index(i) => Value::from(*i),
            })
            .collect();
        map.insert("path".into(), Value::Array(path));
        map.insert("message".into(), Value::from(self.message.clone()));
        Value::Object(map)
    }

    /// Zod's `toDotPath` rendering of the issue path.
    pub fn dot_path(&self) -> String {
        let mut out = String::new();
        for seg in &self.path {
            match seg {
                PathSeg::Index(i) => out.push_str(&format!("[{i}]")),
                PathSeg::Key(k) => {
                    let identifier = !k.is_empty()
                        && !k.starts_with(|c: char| c.is_ascii_digit())
                        && k.chars()
                            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$');
                    if identifier {
                        if !out.is_empty() {
                            out.push('.');
                        }
                        out.push_str(k);
                    } else {
                        out.push_str(&format!("[{}]", Value::from(k.clone())));
                    }
                }
            }
        }
        out
    }
}

/// Format issues the way the MCP SDK's `getParseErrorMessage` does.
pub fn format_issues(issues: &[Issue]) -> String {
    issues
        .iter()
        .map(|issue| {
            if issue.path.is_empty() {
                issue.message.clone()
            } else {
                format!("{} at {}", issue.message, issue.dot_path())
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// `ZodError.message`: pretty-printed JSON array of issues.
pub fn issues_json(issues: &[Issue]) -> String {
    let array = Value::Array(issues.iter().map(Issue::to_json).collect());
    serde_json::to_string_pretty(&array).unwrap_or_default()
}

/// Validate `value` (`None` = `undefined`) and return the parsed output.
pub fn validate(schema: &Value, value: Option<&Value>) -> Result<Value, Vec<Issue>> {
    let mut issues = Vec::new();
    let mut path = Vec::new();
    let output = check(schema, value, &mut path, &mut issues);
    if issues.is_empty() {
        Ok(output.unwrap_or(Value::Null))
    } else {
        Err(issues)
    }
}

/// Validate with a path prefix (used for request parameter errors).
pub fn validate_at(
    schema: &Value,
    value: Option<&Value>,
    prefix: &[&str],
) -> Result<Value, Vec<Issue>> {
    let mut issues = Vec::new();
    let mut path: Vec<PathSeg> = prefix
        .iter()
        .map(|k| PathSeg::Key((*k).to_string()))
        .collect();
    let output = check(schema, value, &mut path, &mut issues);
    if issues.is_empty() {
        Ok(output.unwrap_or(Value::Null))
    } else {
        Err(issues)
    }
}

/// A copy of `schema` with `key` removed from `properties` and `required`.
pub fn omit(schema: &Value, key: &str) -> Value {
    let mut copy = schema.clone();
    if let Some(props) = copy.get_mut("properties").and_then(Value::as_object_mut) {
        props.shift_remove(key);
    }
    if let Some(required) = copy.get_mut("required").and_then(Value::as_array_mut) {
        required.retain(|k| k.as_str() != Some(key));
    }
    copy
}

fn received(value: Option<&Value>) -> &'static str {
    match value {
        None => "undefined",
        Some(Value::Null) => "null",
        Some(Value::Bool(_)) => "boolean",
        Some(Value::Number(_)) => "number",
        Some(Value::String(_)) => "string",
        Some(Value::Array(_)) => "array",
        Some(Value::Object(_)) => "object",
    }
}

fn invalid_type(expected: &str, value: Option<&Value>, path: &[PathSeg]) -> Issue {
    Issue::new(
        vec![
            ("expected", Value::from(expected)),
            ("code", Value::from("invalid_type")),
        ],
        path,
        format!(
            "Invalid input: expected {expected}, received {}",
            received(value)
        ),
    )
}

fn invalid_value(values: &[Value], path: &[PathSeg]) -> Issue {
    let message = if values.len() == 1 {
        format!("Invalid input: expected {}", values[0])
    } else {
        let joined = values
            .iter()
            .map(Value::to_string)
            .collect::<Vec<_>>()
            .join("|");
        format!("Invalid option: expected one of {joined}")
    };
    Issue::new(
        vec![
            ("code", Value::from("invalid_value")),
            ("values", Value::Array(values.to_vec())),
        ],
        path,
        message,
    )
}

fn bound_issue(origin: &str, small: bool, limit: f64, inclusive: bool, path: &[PathSeg]) -> Issue {
    let (code, key, word, op) = if small {
        (
            "too_small",
            "minimum",
            "Too small",
            if inclusive { ">=" } else { ">" },
        )
    } else {
        (
            "too_big",
            "maximum",
            "Too big",
            if inclusive { "<=" } else { "<" },
        )
    };
    let limit_text = js::number_to_string(limit);
    let message = match origin {
        "string" => format!("{word}: expected string to have {op}{limit_text} characters"),
        "array" => format!("{word}: expected array to have {op}{limit_text} items"),
        other => format!("{word}: expected {other} to be {op}{limit_text}"),
    };
    Issue::new(
        vec![
            ("origin", Value::from(origin)),
            ("code", Value::from(code)),
            (key, js::num(limit)),
            ("inclusive", Value::from(inclusive)),
        ],
        path,
        message,
    )
}

fn schema_types(schema: &Map<String, Value>) -> Vec<&str> {
    match schema.get("type") {
        Some(Value::String(t)) => vec![t.as_str()],
        Some(Value::Array(ts)) => ts.iter().filter_map(Value::as_str).collect(),
        _ => Vec::new(),
    }
}

fn check(
    schema: &Value,
    value: Option<&Value>,
    path: &mut Vec<PathSeg>,
    issues: &mut Vec<Issue>,
) -> Option<Value> {
    let Some(s) = schema.as_object() else {
        return value.cloned();
    };

    if let Some(branches) = s.get("anyOf").and_then(Value::as_array) {
        let is_null = |b: &Value| b.get("type").and_then(Value::as_str) == Some("null");
        let nullable = branches.iter().any(is_null);
        if nullable && matches!(value, Some(Value::Null)) {
            return Some(Value::Null);
        }
        let others: Vec<&Value> = branches.iter().filter(|b| !is_null(b)).collect();
        if others.len() == 1 {
            return check(others[0], value, path, issues);
        }
        for branch in &others {
            let mut scratch = Vec::new();
            let mut branch_path = path.clone();
            let out = check(branch, value, &mut branch_path, &mut scratch);
            if scratch.is_empty() {
                return out;
            }
        }
        issues.push(Issue::new(
            vec![("code", Value::from("invalid_union"))],
            path,
            "Invalid input".into(),
        ));
        return None;
    }

    let mut types = schema_types(s);
    if types.contains(&"null") && types.len() > 1 {
        if matches!(value, Some(Value::Null)) {
            return Some(Value::Null);
        }
        types.retain(|t| *t != "null");
    }

    if let Some(options) = s.get("enum").and_then(Value::as_array) {
        return match value {
            Some(v) if options.contains(v) => Some(v.clone()),
            _ => {
                issues.push(invalid_value(options, path));
                None
            }
        };
    }

    match types.first().copied() {
        None => value.cloned(),
        Some("object") => check_object(s, value, path, issues),
        Some("array") => check_array(s, value, path, issues),
        Some("string") => check_string(s, value, path, issues),
        Some(kind @ ("number" | "integer")) => {
            check_number(s, kind == "integer", value, path, issues)
        }
        Some("boolean") => match value {
            Some(Value::Bool(b)) => Some(Value::Bool(*b)),
            _ => {
                issues.push(invalid_type("boolean", value, path));
                None
            }
        },
        Some("null") => match value {
            Some(Value::Null) => Some(Value::Null),
            _ => {
                issues.push(invalid_type("null", value, path));
                None
            }
        },
        Some(_) => value.cloned(),
    }
}

fn check_object(
    s: &Map<String, Value>,
    value: Option<&Value>,
    path: &mut Vec<PathSeg>,
    issues: &mut Vec<Issue>,
) -> Option<Value> {
    let is_record = s.contains_key("propertyNames");
    let Some(Value::Object(input)) = value else {
        issues.push(invalid_type(
            if is_record { "record" } else { "object" },
            value,
            path,
        ));
        return None;
    };
    let required: Vec<&str> = s
        .get("required")
        .and_then(Value::as_array)
        .map(|r| r.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let props = s.get("properties").and_then(Value::as_object);
    let before = issues.len();
    let mut out = Map::new();

    if let Some(props) = props {
        for (key, sub) in props {
            let field = input.get(key);
            if field.is_none() && !required.contains(&key.as_str()) {
                continue;
            }
            path.push(PathSeg::Key(key.clone()));
            if let Some(parsed) = check(sub, field, path, issues) {
                out.insert(key.clone(), parsed);
            }
            path.pop();
        }
    }
    let known = |key: &str| props.is_some_and(|p| p.contains_key(key));

    match s.get("additionalProperties") {
        Some(Value::Bool(true)) => extend_passthrough(&mut out, input, known),
        Some(Value::Object(extra)) if extra.is_empty() => {
            extend_passthrough(&mut out, input, known)
        }
        Some(extra @ Value::Object(_)) => {
            let key_enum = s
                .get("propertyNames")
                .and_then(|p| p.get("enum"))
                .and_then(Value::as_array);
            for (key, field) in input {
                if known(key) {
                    continue;
                }
                if let Some(keys) = key_enum
                    && !keys.iter().any(|k| k.as_str() == Some(key))
                {
                    issues.push(Issue::new(
                        vec![
                            ("code", Value::from("unrecognized_keys")),
                            ("keys", Value::Array(vec![Value::from(key.clone())])),
                        ],
                        path,
                        format!("Unrecognized key: \"{key}\""),
                    ));
                    continue;
                }
                path.push(PathSeg::Key(key.clone()));
                if let Some(parsed) = check(extra, Some(field), path, issues) {
                    out.insert(key.clone(), parsed);
                }
                path.pop();
            }
            for key in &required {
                if !known(key) && !input.contains_key(*key) {
                    path.push(PathSeg::Key((*key).to_string()));
                    check(extra, None, path, issues);
                    path.pop();
                }
            }
        }
        _ => {}
    }

    (issues.len() == before).then_some(Value::Object(out))
}

fn extend_passthrough(
    out: &mut Map<String, Value>,
    input: &Map<String, Value>,
    known: impl Fn(&str) -> bool,
) {
    for (key, field) in input {
        if !known(key) {
            out.insert(key.clone(), field.clone());
        }
    }
}

fn check_array(
    s: &Map<String, Value>,
    value: Option<&Value>,
    path: &mut Vec<PathSeg>,
    issues: &mut Vec<Issue>,
) -> Option<Value> {
    let Some(Value::Array(items)) = value else {
        issues.push(invalid_type("array", value, path));
        return None;
    };
    let before = issues.len();
    let item_schema = s.get("items").cloned().unwrap_or(Value::Object(Map::new()));
    let mut out = Vec::with_capacity(items.len());
    for (index, item) in items.iter().enumerate() {
        path.push(PathSeg::Index(index));
        if let Some(parsed) = check(&item_schema, Some(item), path, issues) {
            out.push(parsed);
        }
        path.pop();
    }
    let len = items.len() as f64;
    if let Some(min) = s.get("minItems").and_then(Value::as_f64)
        && len < min
    {
        issues.push(bound_issue("array", true, min, true, path));
    }
    if let Some(max) = s.get("maxItems").and_then(Value::as_f64)
        && len > max
    {
        issues.push(bound_issue("array", false, max, true, path));
    }
    (issues.len() == before).then_some(Value::Array(out))
}

fn check_string(
    s: &Map<String, Value>,
    value: Option<&Value>,
    path: &[PathSeg],
    issues: &mut Vec<Issue>,
) -> Option<Value> {
    let Some(Value::String(text)) = value else {
        issues.push(invalid_type("string", value, path));
        return None;
    };
    let before = issues.len();
    let len = js::js_len(text) as f64;
    if let Some(min) = s.get("minLength").and_then(Value::as_f64)
        && len < min
    {
        issues.push(bound_issue("string", true, min, true, path));
    }
    if let Some(max) = s.get("maxLength").and_then(Value::as_f64)
        && len > max
    {
        issues.push(bound_issue("string", false, max, true, path));
    }
    if let Some(pattern) = s.get("pattern").and_then(Value::as_str)
        && !matches_pattern(pattern, text)
    {
        let datetime = s.get("format").and_then(Value::as_str) == Some("date-time");
        let (format, message) = if datetime {
            ("datetime", "Invalid ISO datetime".to_string())
        } else {
            ("regex", pattern_message(pattern))
        };
        issues.push(Issue::new(
            vec![
                ("origin", Value::from("string")),
                ("code", Value::from("invalid_format")),
                ("format", Value::from(format)),
                ("pattern", Value::from(format!("/{pattern}/"))),
            ],
            path,
            message,
        ));
    }
    (issues.len() == before).then(|| Value::String(text.clone()))
}

fn pattern_message(pattern: &str) -> String {
    match pattern {
        ID_PATTERN => {
            "ID must contain only alphanumeric characters, hyphens, and underscores".into()
        }
        ISO_PATTERN => "Expected ISO 8601 date in YYYY-MM-DD or full datetime format.".into(),
        other => format!("Invalid string: must match pattern /{other}/"),
    }
}

fn check_number(
    s: &Map<String, Value>,
    integer: bool,
    value: Option<&Value>,
    path: &[PathSeg],
    issues: &mut Vec<Issue>,
) -> Option<Value> {
    let Some(Value::Number(n)) = value else {
        issues.push(invalid_type("number", value, path));
        return None;
    };
    let x = n.as_f64().unwrap_or(f64::NAN);
    if integer {
        if x.fract() != 0.0 {
            issues.push(Issue::new(
                vec![
                    ("expected", Value::from("int")),
                    ("format", Value::from("safeint")),
                    ("code", Value::from("invalid_type")),
                ],
                path,
                "Invalid input: expected int, received number".into(),
            ));
            return None;
        }
        if x > MAX_SAFE_INTEGER || x < -MAX_SAFE_INTEGER {
            let small = x < 0.0;
            let limit = if small {
                -MAX_SAFE_INTEGER
            } else {
                MAX_SAFE_INTEGER
            };
            issues.push(bound_issue("int", small, limit, true, path));
            return None;
        }
    }
    let before = issues.len();
    let is_safe_bound = |limit: f64| integer && limit.abs() == MAX_SAFE_INTEGER;
    if let Some(min) = s.get("minimum").and_then(Value::as_f64)
        && !is_safe_bound(min)
        && x < min
    {
        issues.push(bound_issue("number", true, min, true, path));
    }
    if let Some(min) = s.get("exclusiveMinimum").and_then(Value::as_f64)
        && x <= min
    {
        issues.push(bound_issue("number", true, min, false, path));
    }
    if let Some(max) = s.get("maximum").and_then(Value::as_f64)
        && !is_safe_bound(max)
        && x > max
    {
        issues.push(bound_issue("number", false, max, true, path));
    }
    if let Some(max) = s.get("exclusiveMaximum").and_then(Value::as_f64)
        && x >= max
    {
        issues.push(bound_issue("number", false, max, false, path));
    }
    (issues.len() == before).then(|| Value::Number(n.clone()))
}

// ---------------------------------------------------------------------------
// Patterns (the four regular expressions used by the advertised schemas)
// ---------------------------------------------------------------------------

/// Whether `pattern` is one of the supported advertised patterns.
pub fn is_known_pattern(pattern: &str) -> bool {
    matches!(
        pattern,
        ID_PATTERN | OFFSET_PATTERN | ISO_PATTERN | DATETIME_PATTERN
    )
}

fn matches_pattern(pattern: &str, text: &str) -> bool {
    match pattern {
        ID_PATTERN => is_record_id(text),
        OFFSET_PATTERN => is_offset(text),
        ISO_PATTERN => is_iso_8601(text),
        DATETIME_PATTERN => is_zod_datetime(text),
        _ => false,
    }
}

/// `/^[a-zA-Z0-9_-]+$/`
pub fn is_record_id(text: &str) -> bool {
    !text.is_empty()
        && text
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'_' || b == b'-')
}

fn digit(b: u8) -> bool {
    b.is_ascii_digit()
}

/// `/^[+-](?:0\d|1[0-4]):[0-5]\d$/`
pub fn is_offset(text: &str) -> bool {
    let b = text.as_bytes();
    b.len() == 6
        && matches!(b[0], b'+' | b'-')
        && ((b[1] == b'0' && digit(b[2])) || (b[1] == b'1' && (b'0'..=b'4').contains(&b[2])))
        && b[3] == b':'
        && (b'0'..=b'5').contains(&b[4])
        && digit(b[5])
}

fn all_digits(b: &[u8]) -> bool {
    b.iter().copied().all(digit)
}

/// `ISO_8601_REGEX` from the TypeScript date utilities.
pub fn is_iso_8601(text: &str) -> bool {
    let b = text.as_bytes();
    if b.len() < 10
        || !all_digits(&b[0..4])
        || b[4] != b'-'
        || !all_digits(&b[5..7])
        || b[7] != b'-'
        || !all_digits(&b[8..10])
    {
        return false;
    }
    let rest = &b[10..];
    if rest.is_empty() {
        return true;
    }
    if rest.len() < 9
        || rest[0] != b'T'
        || !all_digits(&rest[1..3])
        || rest[3] != b':'
        || !all_digits(&rest[4..6])
        || rest[6] != b':'
        || !all_digits(&rest[7..9])
    {
        return false;
    }
    let mut tail = &rest[9..];
    if tail.first() == Some(&b'.') {
        let frac = tail[1..].iter().take_while(|c| digit(**c)).count();
        if !(1..=3).contains(&frac) {
            return false;
        }
        tail = &tail[1 + frac..];
    }
    match tail {
        [] | [b'Z'] => true,
        [sign, h1, h2, b':', m1, m2] => {
            matches!(sign, b'+' | b'-') && all_digits(&[*h1, *h2, *m1, *m2])
        }
        _ => false,
    }
}

fn two(b: &[u8]) -> Option<u32> {
    (b.len() == 2 && all_digits(b)).then(|| u32::from(b[0] - b'0') * 10 + u32::from(b[1] - b'0'))
}

/// Zod's `z.string().datetime({ offset: true })` pattern.
pub fn is_zod_datetime(text: &str) -> bool {
    let b = text.as_bytes();
    if b.len() < 20 || !all_digits(&b[0..4]) || b[4] != b'-' || b[7] != b'-' || b[10] != b'T' {
        return false;
    }
    let year: u32 = text[0..4].parse().unwrap_or(0);
    let (Some(month), Some(day)) = (two(&b[5..7]), two(&b[8..10])) else {
        return false;
    };
    let leap = year.is_multiple_of(4) && (!year.is_multiple_of(100) || year.is_multiple_of(400));
    let max_day = match month {
        1 | 3 | 5 | 7 | 8 | 10 | 12 => 31,
        4 | 6 | 9 | 11 => 30,
        2 if leap => 29,
        2 => 28,
        _ => return false,
    };
    if day < 1 || day > max_day {
        return false;
    }
    let (Some(hour), Some(minute), Some(second)) =
        (two(&b[11..13]), two(&b[14..16]), two(&b[17..19]))
    else {
        return false;
    };
    if b[13] != b':' || b[16] != b':' || hour > 23 || minute > 59 || second > 59 {
        return false;
    }
    let mut tail = &b[19..];
    if tail.first() == Some(&b'.') {
        let frac = tail[1..].iter().take_while(|c| digit(**c)).count();
        if frac == 0 {
            return false;
        }
        tail = &tail[1 + frac..];
    }
    match tail {
        [b'Z'] => true,
        [sign, h1, h2, b':', m1, m2] => {
            let (Some(oh), Some(om)) = (two(&[*h1, *h2]), two(&[*m1, *m2])) else {
                return false;
            };
            matches!(sign, b'+' | b'-') && oh <= 23 && om <= 59
        }
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn strips_unknown_keys_and_orders_by_shape() {
        let schema = json!({"type": "object", "properties": {"a": {"type": "number"}, "c": {"type": "object", "properties": {"x": {"type": "number"}}, "required": ["x"], "additionalProperties": false}}, "required": ["a", "c"], "additionalProperties": {}});
        let out = validate(
            &schema,
            Some(&json!({"extra": 1, "c": {"y": 2, "x": 1}, "a": 2})),
        )
        .unwrap();
        assert_eq!(
            serde_json::to_string(&out).unwrap(),
            r#"{"a":2,"c":{"x":1},"extra":1}"#
        );
    }

    #[test]
    fn reports_zod_messages() {
        let schema = json!({"type": "object", "properties": {
            "metric": {"type": "string", "enum": ["recovery", "hrv"]},
            "days": {"type": "integer", "minimum": 7, "maximum": 90},
            "id": {"type": "string", "pattern": ID_PATTERN}
        }, "required": ["metric"]});
        let issues = validate(
            &schema,
            Some(&json!({"metric": "bogus", "days": 3, "id": "a b"})),
        )
        .unwrap_err();
        assert_eq!(
            format_issues(&issues),
            "Invalid option: expected one of \"recovery\"|\"hrv\" at metric\nToo small: expected number to be >=7 at days\nID must contain only alphanumeric characters, hyphens, and underscores at id"
        );
        let issues = validate(&schema, None).unwrap_err();
        assert_eq!(
            format_issues(&issues),
            "Invalid input: expected object, received undefined"
        );
        let issues = validate(&schema, Some(&json!({"metric": "hrv", "days": 7.5}))).unwrap_err();
        assert_eq!(
            format_issues(&issues),
            "Invalid input: expected int, received number at days"
        );
    }

    #[test]
    fn exhaustive_enum_records_require_all_keys() {
        let schema = json!({"type": "object", "propertyNames": {"type": "string", "enum": ["p", "q"]}, "additionalProperties": {"type": ["number", "null"]}, "required": ["p", "q"]});
        let issues = validate(&schema, Some(&json!({"p": 1}))).unwrap_err();
        assert_eq!(
            format_issues(&issues),
            "Invalid input: expected number, received undefined at q"
        );
        assert!(validate(&schema, Some(&json!({"p": 1, "q": null}))).is_ok());
    }

    #[test]
    fn patterns_match_their_regular_expressions() {
        assert!(
            is_offset("+05:30")
                && is_offset("-14:00")
                && !is_offset("+15:00")
                && !is_offset("+0530")
        );
        assert!(is_iso_8601("2024-01-01") && is_iso_8601("2024-01-01T10:00:00.123+05:30"));
        assert!(!is_iso_8601("2024-01-01T10:00:00.1234Z") && !is_iso_8601("2024-01-01T10:00"));
        assert!(
            is_zod_datetime("2024-02-29T00:00:00Z") && !is_zod_datetime("2023-02-29T00:00:00Z")
        );
        assert!(
            is_zod_datetime("2000-02-29T23:59:59.123456+05:30")
                && !is_zod_datetime("1900-02-29T00:00:00Z")
        );
        assert!(
            !is_zod_datetime("2024-01-01T24:00:00Z") && !is_zod_datetime("2024-01-01T10:00:00")
        );
        assert!(is_record_id("abc-DEF_123") && !is_record_id("") && !is_record_id("a b"));
    }

    #[test]
    fn issue_json_matches_zod_shape() {
        let schema = json!({"type": "string"});
        let issues = validate_at(&schema, None, &["params", "name"]).unwrap_err();
        assert_eq!(
            issues_json(&issues),
            "[\n  {\n    \"expected\": \"string\",\n    \"code\": \"invalid_type\",\n    \"path\": [\n      \"params\",\n      \"name\"\n    ],\n    \"message\": \"Invalid input: expected string, received undefined\"\n  }\n]"
        );
    }
}
